### ISSUE TITLE
[series] database

### ISSUE THREAD

**Issue by ambersun1234** [ambersun1234/ambersun1234.github.io#4]
https://github.com/ambersun1234/chirpy.ambersun1234.github.io/issues/8

+ [ ] sql, nosql, newsql
+ [ ] ER model
+ [ ] elastic search
+ [ ] lock

<hr>

+ [x] b+ tree
+ [x] b tree, hash index
+ [x] table scan

<hr>

+ [x] delayed queue
    + [x] mq #4
    + [x] redis #4
    + [x] priority queue #14 
    + [x] polling #12 

<hr>

+ [x] minio
    + [x] quorum #4
    + [x] rabbitmq #4
    + [x] pbac #10 
    + [x] webhook
    + [x] lifecycle management

<hr>

+ [ ] software optimization
    + [x] index #4
    + [ ] store procedure
    + [ ] regex, like
    + [ ] container
    + [ ] image store location
+ [x] hardware optimization
    + [x] index #4 
    + [x] CAP
    + [x] scale out, up
    + [ ] store procedure #4 
    + [x] distributed issue #4
+ [x] distributed issue
    + [x] clock #5
    + [x] 51% attack #1 
    + [x] #12 long polling

<hr>

+ [x] n + 1

<hr>

+ [x] cache
    + [x] transaction #4
    + [x] gil #12 
    + [x] message queue
    + [x] memcached
    + [x] minio #4
    + [x] cluster
        + [x] kafka #4
        + [x] redis #4
        + [x] consensus #4
        + [x] #13 pub/sub
    + [x] probabilistic data structure #12 

<hr>

+ [x] message queue
    + [x] apache kafka
    + [x] #13 publisher-subscriber pattern
    + [x] #12 ipc
    + [x] #10 grpc
    + [x] sequential io
    + [x] single leader replication #4
    + [x] polling #12
    + [x] zookeeper, kraft

<hr>

+ [x] transaction, isolation
    + [x] gil #12 
    + [x] cache #4

+ [x] migration
    + [x] transaction #4
    + [x] distributed database #4
    + [x] kafka #4
    + [x] #3 blue green deployment

+ [ ] atlas
    + [x] migration #4
    + [x] transaction #4
    + [x] controller #3 

<hr>

+ [x] cursor based pagination
    + [x] index #4

<hr>

+ [x] sticky session

<hr>

+ [x] postgresql

<hr>

+ [x] fuzzy search

**Comment by ambersun1234** [comment]
+ https://dev.to/harmeetsingh/is-it-safe-to-expose-mongodb-objectid-in-urls-apis-38l
+ https://stackoverflow.com/questions/28895067/using-uuids-instead-of-objectids-in-mongodb
+ https://stackoverflow.com/questions/29881896/why-do-we-need-relationships-between-tables-at-all
+ https://dba.stackexchange.com/questions/162263/what-does-the-word-sargable-really-mean
+ https://stackoverflow.com/questions/8729779/why-nosql-is-better-at-scaling-out-than-rdbms

**Comment by ambersun1234** [comment]
cache policy add description, https://media.licdn.com/dms/image/D4E22AQEyYrPAujIHFA/feedshare-shrink_800/0/1690127110189?e=1692835200&v=beta&t=UJ4q9rKhebrpkwbRXsrGIV6N3NhG9mu4jbWKbOrrk6s
